repos:
- repo: https://github.com/pycqa/flake8
  rev: '5.0.4'  # pick a git hash / tag to point to
  hooks:
    - id: flake8
      stages: [commit-msg]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: 'v9.1.0'
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']